# Generated by Django 3.1.3 on 2021-07-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blinkdata',
            name='id',
        ),
        migrations.DeleteModel(
            name='DailyTodo',
        ),
        migrations.RemoveField(
            model_name='drowsinessdata',
            name='id',
        ),
        migrations.DeleteModel(
            name='Freeboard',
        ),
        migrations.DeleteModel(
            name='Questionboard',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='BlinkData',
        ),
        migrations.DeleteModel(
            name='DrowsinessData',
        ),
    ]
