# Generated by Django 3.1.3 on 2021-07-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_blinkd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentQuestionboard',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='TaskManager.questionboard')),
                ('uid', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('comments', models.TextField()),
                ('username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'comment_questionboard',
                'managed': False,
            },
        ),
    ]
